sudo apt update -y
sudo apt upgrade -y
sudo apt install git -y
sudo apt install airgeddon -y
sudo apt install whatweb -y
sudo apt install wpscan -y
sudo apt install proxychains4 -y
sudo apt install tor -y
sudo apt install linux-headers-amd64 
sudo apt install linux-headers-6.6.9-amd64
git clone https://github.com/tegal1337/CiLocks
sudo apt install virtualbox-qt -y
sudo apt install code-oss -y
sudo apt install rkhunter -y
sudo apt install metasploit-framework -y
sudo apt install dirb -y
sudo apt install hydra -y
sudo apt install nmap -y
sudo apt install zmap -y
sudo apt install recon-ng -y
sudo apt install john -y
sudo apt install armitage -y
sudo apt install aircrack-ng -y
sudo apt install wifite -y
sudo apt install wpscan -y
sudo apt install hashcat -y
sudo apt install sherlock -y
sudo apt install spiderfoot -y
sudo apt install legion -y
sudo apt install maltego -y
sudo apt install beef-xss -y
sudo apt install yara -y
sudo apt install fcrackzip -y
sudo apt install sqlmap -y
sudo apt install tcpdump -y
sudo apt install ettercap -y
sudo apt install burpsuite -y
sudo apt install ettercap -y
sudo apt install wireshark -y
sudo apt install binwalk -y
sudo apt install wifiphisher -y
sudo apt install netdiscover -y
sudo apt install firewalk -y
sudo apt install nikto -y
sudo apt install fping -y
sudo apt install arpwatch -y
sudo apt install scapy -y
sudo apt install bed -y
sudo apt install doona -y 
sudo apt install cisco-ocs -y
sudo apt install dotdotpwn -y
sudo apt install sfuzz -y
sudo apt install sqlsus -y
sudo apt install tnscmd10g -y
sudo apt install sidguesser -y
sudo apt install siparmyknife -y
sudo apt install arpwatch -y
sudo apt install bulk-extractor -y
sudo apt install chntpw -y
sudo apt install dumpzilla -y
sudo apt install foremost -y
sudo apt install p0f -y
sudo apt install pdf-parser -y
sudo apt install pdfid -y
sudo apt install dc3dd -y
sudo apt install bluelog -y
sudo apt install bully -y
sudo apt install crackle -y
sudo apt install hcxtools -y
sudo apt install mana -y
sudo apt install ipv6-toolkit -y
sudo apt install termineter -y
sudo apt install iaxflood -y
sudo apt install rtpflood -y
sudo apt install wine -y
sudo apt install 0trace -y
sudo apt install i2c-tools -y
sudo apt install qemu -y
sudo apt install 7zip -y
sudo apt install ibombshell -y
sudo apt install ikescan -y
sudo apt install aesfix -y 
sudo apt install aeskeyfind -y
sudo apt install afflib -y
sudo apt install impacket -y
sudo apt install burpsuite -y
sudo apt install apktool -y
sudo apt install armitage -y
sudo apt install arp-scan -y
sudo apt install wpscan -y
sudo apt install whatweb -y
sudo apt install javasnoop -y
sudo apt install atftp -y
sudo apt install rake -y
sudo apt install autopsy -y
sudo apt install axel -y
sudo apt install reaver -y
sudo apt install b274k -y
sudo apt install backdoor-factory -y
sudo apt install redeye -y
sudo apt install redfang -y
sudo apt install bluesnarfer -y
sudo apt install blue-hydra -y
sudo apt install robotstxt -y
sudo apt install golang -y
sudo apt install g++ -y
sudo apt install ruby -y
sudo apt install jsql -y
sudo apt install juice-shop -y
sudo apt install routersploit -y
sudo apt install samba -y
sudo apt install brutespray -y
sudo apt install exiftool -y
sudo apt install bruteshark -y
sudo apt install cadaver -y 
sudo apt install ccrypt -y
sudo apt install capstone -y
sudo apt install cewl -y
sudo apt install chktoolkit -y
sudo apt install kismet -y
sudo apt install knocker -y
sudo apt install legion -y
sudo apt install libewf -y
sudo apt install commix -y
sudo apt install skipfish -y
sudo apt install go -y
sudo apt install dirbuster -y
sudo apt install crack -y
sudo apt install axel -y
sudo apt install cryptcat -y
sudo apt install slimtoolkit -y
sudo apt install silver -y
sudo apt install rkhunter -y
sudo apt install sniffjoke -y
sudo apt install cupid-wpa -y
sudo apt install socat -y
sudo apt install sploitscan -y
sudo apt install ssldump -y
sudo apt install dmitry -y
sudo apt install dnscat2 -y
sudo apt install sqlninja -y
sudo apt install mac-robber -y
sudo apt install macchanger -y
sudo apt install ettercap -y
sudo apt install tcpflow -y
sudo apt install ethtool -y
sudo apt install evil-sspd -y
sudo apt install evilginx2 -y 
sudo apt install exe2hexbat -y
sudo apt install exifprobe -y
sudo apt install mdbtools -y
sudo apt install tcpick -y
sudo apt install teamsploit -y
sudo apt install merlin -y
sudo apt install lynx -y
sudo apt install w3m -y
sudo apt install metacam -y
sudo apt install mimkatz -y
sudo apt install fatcat -y
sudo apt install fcrackzip -y
sudo apt install fern-wifi-cracker -y
sudo apt install flashrom -y
sudo apt install firewalk -y
sudo apt install mongo-tools -y
sudo apt install tiger -y
sudo apt install framework2 -y
sudo apt install fping -y
sudo apt install forensic-artifacts -y
sudo apt install nasm -y
sudo apt install ubertooth -y
sudo apt install ghydra -y
sudo apt install netmask -y
sudo apt install netsniff-ng -y
sudo apt install unicornscan -y
sudo apt install gophish -y
sudo apt update -y
sudo apt full-upgrade -y
